import { Metadata } from "next";

import { RegisterStoreProvider } from "@/providers/RegisterProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <RegisterStoreProvider>{children}</RegisterStoreProvider>
    </>
  );
}
